//ACTIONS ON REVIEWS
export const GET_COMPANY_REVIEWS = 'GET_COMPANY_REVIEWS';
export const GET_COMPANY_REVIEWS_SUCCESS = 'GET_COMPANY_REVIEWS_SUCCESS';
export const GET_COMPANY_REVIEWS_FAILURE = 'GET_COMPANY_REVIEWS_FAILURE';

export const GET_SALARY_REVIEWS = 'GET_SALARY_REVIEWS';
export const GET_SALARY_REVIEWS_SUCCESS = 'GET_SALARY_REVIEWS_SUCCESS';
export const GET_SALARY_REVIEWS_FAILURE = 'GET_SALARY_REVIEWS_FAILURE';

export const GET_INTERVIEW_REVIEWS = 'GET_INTERVIEW_REVIEWS';
export const GET_INTERVIEW_REVIEWS_SUCCESS = 'GET_INTERVIEW_REVIEWS_SUCCESS';
export const GET_INTERVIEW_REVIEWS_FAILURE = 'GET_INTERVIEW_REVIEWS_FAILURE';


//ACTION TYPES FOR AUTH
export const LOG_IN_USER = 'LOG_IN_USER_REVIEWS';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
