// ACTIONS ON REVIEWS
export const GET_COMPANY_REVIEWS = 'GET_COMPANY_REVIEWS';
export const GET_COMPANY_REVIEWS_SUCCESS = 'GET_COMPANY_REVIEWS_SUCCESS';
export const GET_COMPANY_REVIEWS_FAILURE = 'GET_COMPANY_REVIEWS_FAILURE';

export const DELETE_COMPANY_REVIEWS = 'DELETE_COMPANY_REVIEWS';
export const DELETE_COMPANY_REVIEWS_SUCCESS = 'DELETE_COMPANY_REVIEWS_SUCCESS';
export const DELETE_COMPANY_REVIEWS_FAILURE = 'DELETE_COMPANY_REVIEWS_FAILURE';

export const UPDATE_COMPANY_REVIEWS = 'UPDATE_COMPANY_REVIEWS';
export const UPDATE_COMPANY_REVIEWS_SUCCESS = 'UPDATE_COMPANY_REVIEWS_SUCCESS';
export const UPDATE_COMPANY_REVIEWS_FAILURE = 'UPDATE_COMPANY_REVIEWS_FAILURE';

export const GET_SALARY_REVIEWS = 'GET_SALARY_REVIEWS';
export const GET_SALARY_REVIEWS_SUCCESS = 'GET_SALARY_REVIEWS_SUCCESS';
export const GET_SALARY_REVIEWS_FAILURE = 'GET_SALARY_REVIEWS_FAILURE';

export const GET_INTERVIEW_REVIEWS = 'GET_INTERVIEW_REVIEWS';
export const GET_INTERVIEW_REVIEWS_SUCCESS = 'GET_INTERVIEW_REVIEWS_SUCCESS';
export const GET_INTERVIEW_REVIEWS_FAILURE = 'GET_INTERVIEW_REVIEWS_FAILURE';

// ACTION TYPES FOR AUTH
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const LOG_OUT_USER_SUCCESS = 'LOG_OUT_USER_SUCCESS';
export const LOG_OUT_USER_FAILURE = 'LOG_OUT_USER_FAILURE';

export const EDIT_PROFILE_PICTURE = 'EDIT_PROFILE_PICTURE_REVIEWS';
export const EDIT_PROFILE_PICTURE_SUCCESS = 'EDIT_PROFILE_PICTURE_SUCCESS';
export const EDIT_PROFILE_PICTURE_FAILURE = 'EDIT_PROFILE_PICTURE_FAILURE';

export const GET_INTERESTS = 'GET_INTERESTS';
export const GET_INTERESTS_FAILURE = 'GET_INTERESTS_FAILURE';
export const GET_INTERESTS_SUCCESS = 'GET_INTERESTS_SUCCESS';

export const DELETE_INTEREST = 'DELETE_INTEREST';
export const ADD_INTEREST = 'ADD_INTEREST';

export const GET_JOB_ROLES = 'GET_JOB_ROLES';
export const GET_JOB_ROLES_SUCCESS = 'GET_JOB_ROLES_SUCCESS';
export const GET_JOB_ROLES_FAILURE = 'GET_JOB_ROLES_FAILURE';
